Repository fga-gpp-mds/2018.1-VoxPop-API, pull requests merged in 2018-05, with the labels that each got.

#66 Added id in parliamentary serializer
  api/serializers.py
Labels: MDS, back end, bug, devops, evolution, hotfix, refactor, simple difficulty

#73 Bf02 arrumar bug da edicao de usuario
  api/serializers.py
  api/tests.py
Labels: MDS, back end, bug, hotfix, moderate difficulty, refactor

#86 Procurar deputado seguido
  api/utils.py
  api/views.py
Labels: back end, devops, new feature, simple difficulty
